// Curated, properly-formatted real quotes (short excerpts) for prose mode,
// bundled the way MonkeyType and Keymash ship their quotes (NOT a flaky public
// API). Normalized to clean ASCII. Source: MonkeyType's open english quote set
// (excerpts from various authors), used as short text for typing practice.
export const QUOTES_EN: string[] = [
  "You have the power to heal your life, and you need to know that.",
  "Don't it make you sad to know that life is more than who you are?",
  "Leave something for someone but don't leave someone for something.",
  "The people with ideas have no power and the people with power have no ideas.",
  "You must take life the way it comes at you and make the best of it.",
  "If you don't know what you want, how are you going to know when you get it?",
  "If you have to ask, you will never know. If you know, you need only ask.",
  "Your memory is the glue that binds your life together.",
  "I'm sure there are things you know that you don't even know you know.",
  "You can't use the fire exit because you're not made of fire.",
  "The person that has the most to do with what happens to you is you!",
  "There are darknesses in life and there are lights, and you are one of the lights, the light of all lights.",
  "Sometimes the world as you know it just decides to become something else.",
  "If you only do what you can do, you will never be more than who you are now.",
  "If I have to hear one more time that you did this for the family...",
  "And in the end, the love you take is equal to the love you make.",
  "I've always loved you, and when you love someone, you love the whole person, just as he or she is, and not as you would like them to be.",
  "Memory is a way of holding onto the things you love, the things you are, the things you never want to lose.",
  "You should never, never doubt something that no one is sure of.",
  "Make sure you marry someone who laughs at the same things you do.",
  "If you think that you are going to love something, give it a try.",
  "I have waited lifetimes to find you. Now that you're here I can remind you of the things you've been dreaming, times two.",
  "Are you trying to impress me? What would impress me more is if you never did that again.",
  "Yeah it's you, you're the one that makes me feel right. I've been in love with her for ages and I can't seem to get it right. I fell in love with her in stages my whole life.",
  "Believe in one thing too much and you have no room for new ideas.",
  "Cleaning your house while kids are around is like shoveling the walk while it's still snowing.",
  "The day the power of love overrules the love of power, the world will know peace.",
  "I am the wisest man alive, for I know one thing, and that is that I know nothing.",
  "You can't convince me what I want and what I need are separate things.",
  "It's easy not to abuse your power when you don't actually have any power.",
  "I often think that men don't understand what is noble and what is ignorant, though they always talk about it.",
  "Now is the time for resting. Some things are ill to hear when the world's in shadow.",
  "Courage is resistance to fear, mastery of fear - not absence of fear.",
  "There's no reason a fake can't do what the real thing would. And it's possible for a fake to be more real than the real thing.",
  "It matters not how a man dies, but how he lives. The act of dying is not of importance, it lasts so short a time.",
  "There is something about yourself that you don't know.",
  "I am he as you are he as you are me and we are all together.",
  "Anything is edible if you deep fry it long enough.",
  "We know little of who we were, only something of who we are, and nothing of who we may be.",
  "You know when I was a kid I always wanted to be a cowboy, and now knowing I'm going to spend my future in the past sounds like a wonderful way to spend my retirement years.",
  "When we remember, we only get a version of the last time we remember it.",
  "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
  "Where do you think you're going? Because I don't think you're going where you think you're going.",
  "When everyone else was thinking it was time for bed, his mind was telling him it's time to get ahead of the competition.",
  "You must learn from the mistakes of others because you can't possibly live long enough to make them all yourself.",
  "I would rather spend one lifetime with you, than face all the ages of this world alone.",
  "You can get more of what you want with a kind word and a gun than you can with just a kind word.",
  "Thinking you know everything there is to know about something will only hold you back, because it prevents you from learning anything new.",
  "Sometimes it takes heart to write about a thing, doesn't it? To let that thing out of the room way in the back of your mind and put it up there on the screen.",
  "I'm going to take my time. I have all the time in the world.",
  "You are what you are and you are where you are because of what has gone into your mind. You change what you are and you change where you are by changing what goes into your mind.",
  "There are many things that I would like to say to you but I don't know how.",
  "When you lose the ones you love, you might find it hard to cry. Until it's only you and everybody else has left the room, you might feel what it's like to not know how to feel.",
  "She had waited all her life for something and it had killed her when it found her.",
  "This truth holds me close, rocking me like a child in a mother's arms.",
  "If you didn't have me to rake you over the coals now and then, there wouldn't be any fire in your life at all.",
  "Those who have made something of their lives will always look at those who haven't as clowns.",
  "Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning.",
  "You are the most important thing to me now. The most important thing to me ever.",
  "Believe me, the irony of being a blind art dealer isn't lost on me.",
  "If you don't like how things are, change it! You're not a tree.",
  "I just want to be able to stand up straight for a little while before I get cut down.",
  "Take me up, take me higher, there's a world not far from here. We can dance in desire or we can burn in love tonight. Our hearts are like firestones and when they strike we feel the love.",
  "You don't need a weather man to know which way the wind blows.",
  "The world was reduced to the surface of her skin and her inner self was safe from all bitterness.",
  "You have to keep your mind as wide-open as your eyes, because almost nothing is what it seems.",
  "The world is a dangerous place to live, not because of the people who are evil, but because of the people who don't do anything about it.",
  "Sometimes life is like this dark tunnel. You can't always see the light at the end of the tunnel, but if you just keep moving, you will come to a better place.",
  "Lights up and they know who you are, know who you are. Do you know who you are?",
  "I learnt long ago to hate my enemies, but I've never loved one before.",
  "From there to here, from here to there, funny things are everywhere.",
  "He misses the time he had with you. I miss the time I didn't have.",
  "I know it's a mistake. But there are certain things in life where you know it's a mistake, but you don't really know it's a mistake, because the only way to really know it's a mistake is to make the mistake.",
  "To be able to say how much you love is to love but little.",
  "This day does not belong to one man but to all. Let us together rebuild this world that we may share in the days of peace.",
  "The mark of the immature man is that he wants to die nobly for a cause, while the mark of the mature man is that he wants to live humbly for one.",
  "No one really knows why they're alive until they know what they'd die for.",
  "I came to realize that I had more to offer to this world than just making things that blow up.",
  "For what you see and hear depends a good deal on where you are standing. It also depends on what sort of person you are.",
  "They're surrounding the city to make a fortress so that no one can see what they're up to inside. Our only chance is the element of surprise.",
  "However small the chance might be of striking lucky, the chance was there.",
  "But I really believe that there are more good people on this earth than bad people, and the good people watch out for each other and take care of each other.",
  "There is freedom in coming and going for no other reason than because you can. There is freedom in choosing to sit and be still when everything is always telling you to move, move fast.",
  "No matter where you stand on the long path, right now, try very hard to smile, and be glad you're in the game.",
  "You don't get to choose if you get hurt in this world, but you do have some say in who hurts you.",
  "I'd tell you all you want and more, if the sounds I made could be what you hear.",
  "I think reality is thin, you know, thin as lake ice after a thaw, and we fill our lives with noise and light and motion to hide that thinness from ourselves.",
  "Therefore a man shall leave his father and mother and be joined to his wife, and they shall become one flesh.",
  "If you think anyone is sane, you just don't know enough about them.",
  "Treachery and violence are spears pointed at both ends; they wound those who resort to them worse than their enemies.",
  "You see, the rays from the star pass so near the sun that they get bent on the way to us.",
  "Stop the world and let me off, I'm tired of going round and round. I played the game of love and lost. So stop the world and let me off.",
  "Nothing is more wonderful than the art of being free, but nothing is harder to learn how to use than freedom.",
  "There was never any more inception than there is now, nor any more youth or age than there is now; and will never be any more perfection than there is now, nor any more heaven or hell than there is now.",
  "Never become used to anything you love, it blunts the edge of appreciation.",
  "Maybe, the only thing that has to make sense about being somebody's friend is that you help them be their best self on any given day. That you give them a home when they don't want to be in their own.",
  "For as it is not one swallow or one fine day that makes a spring, so it is not one day or a short time that makes a man blessed and happy.",
  "Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good.",
  "We all require devotion to something more than ourselves for our lives to be endurable.",
  "For all those times you stood by me, for all the truth that you made me see, for all the joy you brought to my life, for all the wrong that you made right.",
  "Was it all put into words, or did both understand that they had the same thing at heart and in their minds, so that there was no need to speak of it aloud, and better not to speak of it?",
  "Learning does not make one learned: there are those who have knowledge and those who have understanding. The first requires memory and the second philosophy.",
  "You don't make history by following the rules, you make it by seizing the moment.",
  "I don't want to live someone else's idea of how to live.",
  "You don't know what's in store, but you know what you're here for.",
  "The great breakthrough in your life comes when you realize that you can learn anything you need to learn to accomplish any goal that you set for yourself.",
  "It seems to me you lived your life like a candle in the wind, never knowing who to cling to when the rain set in. And I would have liked to have known you but I was just a kid.",
  "A book can give you an experience of someone's life in a few hours, and this is far more profitable than any sale that's going on.",
  "You can always build a shrine to all the terrible things in the world, but it doesn't mean that you have to destroy anything that is good.",
  "They had taken it all away from him now, they had turned away from him and there was nothing for him now. He was alone and there was nothing for him.",
  "She was feeling the pressure of the world outside and she wanted to see him and feel his presence beside her and be reassured that she was doing the right thing after all.",
  "Something in the wind has learned my name and it's telling me that things are not the same. In the leaves on the trees and the touch of the breeze there's a pleasing sense of happiness for me.",
  "They don't know our world but they know their own.",
  "I don't think I was wrong to have held on to my secrets for all those years, and I don't think I was wrong to have told them now. Circumstances changed, and once they changed, I changed my mind as well.",
  "If actions speak louder than words I'm the most deafening noise you've heard. I'll be that ringing in your ears that will stick around for years.",
  "I love the ground under his feet, and the air over his head, and everything he touches and every word he says. I love all his looks, and all his actions and him entirely and all together.",
  "You forget what you want to remember and you remember what you want to forget.",
  "Never say anything unless it is worth taking a long time to say.",
  "In every war, there are calms between storms. There will be days when you lose faith in some of us, days when our allies turn against us, but the day will never come if we forsake this planet and its people.",
  "We look not at the things which are what you would call seen, but at the things which are not seen. For the things which are seen are temporal. But the things which are not seen are eternal.",
  "It was one of those March days when the sun shines hot and the wind blows cold: when it is summer in the light, and winter in the shade.",
  "Even good people are great at making bad decisions.",
  "Spend all your time waiting for that second chance, for a break that would make it okay. There's always some reason to feel not good enough and it's hard at the end of the day.",
  "Any man who has the brains to think and the nerve to act for the benefit of the people of the country is considered a radical, by those who are content with stagnation and willing to endure disaster.",
  "I don't believe that anybody feels the way I do about you now.",
  "If you lie and pretend that you like them, you're fine. But if you tell them the truth, you get fired, you can't afford food, and you get shanked for cutting in line at the soup kitchen. And then you die.",
  "A body has one more kind of pull. This pull is such that it will want to stay put all the time. And the more mass it has, the more it will want to stay put.",
  "I don't want to talk about it! Every time I think about something nice, you remind me of bad things. I only want to talk about the nice things.",
  "When it's coming at you like monsters in the night, and you feel the danger that makes you want to hide; when the cards are stacked against you and you're standing on the edge: now's the time.",
  "Certain things, they should stay the way they are. You ought to be able to stick them in one of those big glass cases and just leave them alone.",
  "If you come to a river and find a boat at the edge, you will use that boat and it will serve you well, but once across the river, do you put the boat on your shoulders and carry it with you on the rest of your journey?",
  "Well, we used to look up in the sky and wonder at our place in the stars. Now we just look down and worry about our place in the dirt.",
  "How can you tell me that you're lonely and say for you that the sun don't shine? Let me take you by the hand and lead you through the streets of London. I'll show you something to make you change your mind.",
  "If you think that you are going to love something, give it a try. You're going to kick yourself in the butt for the rest of your life if you don't.",
  "What I really lived for were those evenings when you were alone, and I pretended you were playing just for me. And though you didn't know it, you were giving me some of the happiest hours of my life.",
  "I pray every night that I may live after him; because I would rather be miserable than that he should be - that proves I love him better than myself.",
  "Some say better things will come our way. No matter what they try to say, you were always there for me. Some way, when the sun begins to shine, I hear a song from another time and fade away.",
  "It feels scary to talk, because once the words are out, you can't put them back in. But if you write words and they don't come out the way you want them to, you can erase them and start over.",
  "Then we saw him pick up all the things that were down. He picked up the cake, and the rake, and the gown, and the milk, and the strings, and the books, and the dish, and the fan, and the cup, and the ship, and the fish.",
  "It may sound like music to her. I can do better with my teeth in a cold shower.",
  "What you don't have you don't need it now. What you don't know you can feel it somehow. What you don't have you don't need it now.",
  "Adios rock band that we loved the most, this is a toast to what you did, and all that you were fighting for. Who could do more, when time marches on? Words come and go, we will sing the melodies that you did long ago.",
  "We were sent here for something. And we know that all things work together for good to them that love God, to them who are called according to his purpose.",
  "Sometimes the briefest moments capture us, force us to take them in, and demand that we live the rest of our lives in reference to them.",
  "The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown.",
  "Take time to really think about your excuses and write them down. These are the same excuses that you always use to stop yourself from learning something new.",
  "The worst part of having someone tell you about their vacation is trying to pretend you're happy for them, because no one wants to hear about all the fun they didn't have.",
  "The law clearly states that magic may be used before Muggles in life-threatening situations.",
  "Why would you pay for a cover band when you got the real deal right here, baby?",
  "When someone is crying, of course, the noble thing to do is to comfort them. But if someone is trying to hide their tears, it may also be noble to pretend you do not notice them.",
  "The green eyes, you're the one that I wanted to find and anyone who tried to deny you, must be out of their mind.",
  "One of the great conditions of anger and hatred is, that you must tell and believe lies against the hated object, in order, as we said, to be consistent.",
  "Let us learn to appreciate there will be times when the trees will be bare, and look forward to the time when we may pick the fruit.",
  "But her brain was not interested in the future. Loaded with the past and hungry for more, it left her no room to imagine, let alone plan for, the next day.",
  "She sits in a corner by the door. There must be more I can tell her if she really wants me to help her. I'll do what I can to show her the way, and maybe one day I will free her, though I know no one can see her.",
  "I don't know, you're made of metal, but you have feelings... and that means you have a soul, and souls don't die... Mom says it's something inside of all good things, and that it goes on forever and ever.",
  "There are mysteries to the universe we were never meant to solve. But who we are and why we are here, are not among them. Those answers we carry inside.",
  "There is only one wish on my mind: when this day is through I hope that I will find that tomorrow will be just the same for you and me. All I need will be mine if you are here.",
  "The hills are alive with the sound of music, with songs they have sung for a thousand years. The hills fill my heart with the sound of music. My heart wants to sing every song it hears.",
  "I used to dread getting older because I thought I would not be able to do all the things I wanted to do, but now that I'm older I find that I don't want to do them.",
  "The light and the dark the big and the small. Just keep in mind you need no more at all. You've seen what you were and know what you'll be. You've seen it all, there is no more to see.",
  "There comes a time when we heed a certain call, when the world must come together as one. There are people dying and it's time to lend a hand to life, the greatest gift of all.",
  "Yeah, they got you where they want you. There's a better life and you think about it, don't you? It's a rich man's game no matter what they call it and you spend your life putting money in his wallet.",
  "I have lived my life to the best of my ability. But I have not been able to escape fate, anger, or pain. Bring me the answers and the road that leads to the truth. Reveal to me once and for all, how all of this will end.",
  "When I need to find something out, I just go out and look for somebody that knows more than me, and I go and ask them. Sometimes I ask pretty hard.",
  "Late into the night I write and the pages of my notebook swell from all the words I've pressed onto them. It almost feels like the more I bruise the page the quicker something inside me heals.",
  "Mind is not in any one place. Every cell in this body has its own intelligence. The brain is sitting in your head, but mind is all over the place.",
  "I hope it is true that a man can die and yet not only live in others but give them life, and not only life but that great consciousness of life.",
  "For one thing, time is the very thing that we are least willing to allow.",
  "Doubting someone is not necessarily a bad thing, because it is something that you do to get to know the person better. What is really bad is not being concerned at all.",
  "And remember also that in fighting against man we must not come to resemble him. Even when you have conquered him, do not adopt his vices.",
  "You can't always get what you want, but if you try sometimes you might find you get what you need.",
  "I can take you for a ride on my big green tractor, we can go slow or make it go faster, down through the woods and out to the pasture, long as I'm with you it really don't matter.",
  "It doesn't matter where you go or what you do, I want to spend each moment of the day with you. Look what has happened with just one kiss, I never knew that I could be in love like this.",
  "I can't believe the things I see. The path that I have chosen now has led me to a wall, and with each passing day I feel a little more like something dear was lost.",
  "For the times when we're apart, well, then close your eyes and know these words are coming from my heart and then if you can remember in good times and bad times I'll be on your side forevermore.",
  "I remember how you said that sometimes it gets just a little hard being home. There's sand stuck in my bed and memories in my head, love, I've been trying to let this whole thing go.",
  "If he stayed at home and carried on with his normal life he would be a thousand times superior to these people and could get any of them out of his way just with a kick.",
  "I swear, there is nothing in the world my mother is better at than getting someone to agree to something that in any other universe, they would never ever consider.",
  "He really had been through death, but he had returned because he could not bear the solitude.",
  "In the casino, the cardinal rule is to keep them playing and to keep them coming back. The longer they play, the more they lose, and in the end, we get it all. Running a casino is like robbing a bank with no cops around.",
  "Things didn't turn out the way they're supposed to, but what can you do? You must take life the way it comes at you and make the best of it.",
  "Then suddenly the humour of the situation came into my mind: the thought of the years I had spent in study and toil to get into the future age, and now my passion of anxiety to get out of it.",
  "Education is the most powerful weapon which you can use to change the world.",
  "Think of what you're saying, you can get it wrong and still you think that it's alright. Think of what I'm saying, we can work it out and get it straight or say good night.",
  "May you find the power in understanding the journey of others to help create your own.",
  "If you can hear this, you're alone. The only thing left of me is the sound of my voice. I don't know if any of us made it. So let me tell you who we were. And how we fought back.",
  "A long, long time ago. I can still remember how that music used to make me smile. And I knew if I had my chance, that I could make those people dance, and maybe they'd be happy for a while.",
  "And now it's time for Silly Songs with Larry, the part of the show where Larry comes out and sings a silly song.",
  "You plonker, you think I don't know a toilet when I see one? You were going to flush me down the loo.",
  "In a business like this the people with the power are the ones that have the understanding of what's going on, not necessarily the ones on top.",
  "I wouldn't hold my breath if I was you, you broke my heart and there's nothing you can do. And now you know, now you know, true friends stab you in the front.",
  "As happens sometimes, a moment settled and hovered and remained for much more than a moment. And sound stopped and movement stopped for much, much more than a moment.",
  "A few minutes ago, I almost made the biggest mistake of my professional life and it was because I was doing something that just wasn't me.",
  "I never should have told you, I never should have let you see inside, don't want it troubling in your mind. Won't you let it be?",
  "It is unwise to make something permanent when the whole world is shifting. There may be a time when this symbol means something treacherous and terrible, rather than something noble and literate.",
  "Few other griefs amid the ill chances of this world have more bitterness and shame for a man's heart than to behold the love of a lady so fair and brave that cannot be returned.",
  "Spring is the time of year when it is summer in the sun and winter in the shade.",
  "When you meet the right person, you know it. You can't stop thinking about them. They are your best friend, and your soulmate. You can't wait to spend the rest of your life with them. No one and nothing else can compare.",
  "You can have success or excuses, but you can't have them both.",
  "The blade is as good as though it had just come out of the grindstone.",
  "Say what you will. But a person just cannot know what he doesn't know. And you can't always see that a bad thing is going to happen before it happens. If you could, no bad would ever come.",
  "When you find that one person who connects you to the world, you become someone different. Someone better. When that person is taken from you, what do you become then?",
  "Losing you would end my life you see, 'cause you mean that much to me. You could have told me yourself that you loved someone else.",
  "People don't suffer from insanity, they love every minute of it.",
  "With the money they earn they'll be able to buy more police and political power. Then they come after us. Right now we have the unions and we have the gambling and those are the best things to have.",
  "I learned to write because I am one of those people who somehow cannot manage the common communications of smiles and gestures, but must use words to get across things that other people would never need to say.",
  "The weird thing about houses is that they almost always look like nothing is happening inside of them, even though they contain most of our lives. I wondered if that was sort of the point of architecture.",
  "I find myself so furious at all these people that I am in contact with just for controlling me or whatever but you know they are not even aware they are doing it.",
  "I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.",
  "You get tough like me and you don't get hurt. You look out for yourself and nothin' can touch you...",
  "Sometimes I'll start a sentence and I don't even know where it's going. I just hope that I find it along the way.",
  "They say that money doesn't bring you happiness, I say neither does being broke, so let me suffer with a new car.",
  "I could work at a problem for years, but to wait inactive for twenty-four hours - that is another matter.",
  "What's the use you learning to do right when it's troublesome to do right and ain't no trouble to do wrong, and the wages is just the same?",
  "Maybe I will never be all the things that I wanna be. Now is not the time to cry, now's the time to find out why. I think you're the same as me, we see things they'll never see.",
  "And when he came to, he was flat on his back on the beach in the freezing sand, and it was raining out of a low sky, and the tide was way out.",
  "I told him that you were really smart. And they'll figure it out soon enough. In the beginning, I thought you might want to be treated like any other kid.",
  "I don't know what it is that makes me love you so. I only know I never want to let you go 'cause you started something. Can't you see that ever since we met you've had a hold on me?",
  "All age brings is space between your words and what they mean and sighs of sympathy. These years are rings with time to grieve alone and in your bed sick of what's in your head. All your worries gone.",
  "You never know what a day will bring, which is both the good news and the bad news of life.",
  "Sometimes it's the very people who no one imagines anything of who do the things that no one can imagine.",
  "There was a little boy once upon a time who in spite of his young age and small size knew his mind. For every copper penny and clover he would find, he'd make a wish for better days and the end of hard times.",
  "Now that I've tried to talk to you and make you understand. All you have to do is close your eyes and just reach out your hands and touch me. Hold me close don't ever let me go.",
  "There is nothing sweeter in this sad world than the sound of someone you love calling your name.",
  "What you need to learn, children, is the difference between right and wrong in every area of life. And once you learn the difference, you must always choose the right.",
  "When has anyone ever told me I had the right to stop it all without my knuckles, or my anger, with just some simple words.",
  "You know no one and no one knows you, and at the same time you don't feel like a stranger. But here you know everyone and everyone knows you, and yet you are a stranger.",
  "And it's whispered that soon, if we all call the tune, then the piper will lead us to reason and a new day will dawn for those who stand long and the forests will echo with laughter.",
  "Now that I look back, I don't know why I was so stressed about it all this time. Funny how sometimes you worry a lot about something and it turns out to be nothing.",
  "I've been looking so long at these pictures of you that I almost believe that they're real. I've been living so long with my pictures of you that I almost believe that the pictures are all I can feel.",
  "Now I see fire inside the mountain, I see fire burning the trees, and I see fire hollowing souls. I see fire, blood in the breeze, and I hope that you remember me.",
  "It's sad to say that kids unaccepted by their peers really never learn how to get along with people in the big grown up world.",
  "Why is it that when you awake to the world of realities you nearly always feel, sometimes very vividly, that the vanished dream has carried with it some enigma which you have failed to solve?",
  "I just watched the man that I love go to prison so that none of you have to, and it hasn't been five minutes and you're already ripping each other apart.",
  "Every thought and every word works for you or against you, and every thought that you confirm to be true becomes a belief. When you change a belief, you change a mental construction and, therefore, your life.",
  "The poor and the middle class work for money. The rich have money work for them.",
  "If a person can't answer directly to your question, it's either the answer is too painful for you to know or too hard for them to admit.",
  "These memories lose their meaning when I think of love as something new, though I know I'll never lose affection for people and things that went before. I know I'll often stop and think about them.",
  "Look, there's only one thing worse than being a loser. It's being one of those guys that sits in a bar, telling the story of how he became a loser, and I never want that to happen to me.",
  "So you run and you run to catch up with the sun but it's sinking, racing around to come up behind you again. The sun is the same in a relative way but you're older, shorter of breath and one day closer to death.",
  "I don't want to live someone else's idea of how to live. Don't ask me to do that. I don't want to find out one day that I'm at the end of someone else's life.",
  "But when you lose something you love, faith takes over. You have to pay attention to what you lost. You have to undo the expectation.",
  "As a young child my mother told me I could be anyone I want to be. Turns out this is called identity theft.",
  "What is this place, and who am I? I don't remember my name. All I remember is that I don't know my name and that I can't remember if I do know my name. I have this strange feeling that I've forgotten all of this before.",
  "And certainly, the mistakes that we male and female mortals make when we have our own way might fairly raise some wonder that we are so fond of it.",
  "She can lead you to love, she can take you or leave you, she can ask for the truth, but she'll never believe. And she'll take what you give her as long as it's free.",
  "Just because something bears the aspect of the inevitable one should not, therefore, go along willingly with it.",
  "I'm on the top of the world looking down on creation and the only explanation I can find is the love that I've found ever since you've been around. Your love's put me at the top of the world.",
  "We fell in love, we had our fun, you always had enough dreams for both of us. I wonder what would come of us if we could trade these ends for beginnings.",
  "Gonna see the river man, gonna tell him all I can about the ban on feeling free. If he tells me all he knows about the way his river flows, I don't suppose it's meant for me.",
  "Your future hasn't been written yet; no one's has. Your future is whatever you make it, so make it a good one.",
  "Educators say that understanding is the key to learning, but how do you understand something if you can't remember it?",
  "If you come soon you'll find breakfast on the table. If you come late you'll get grass and rain-water!",
  "And brace for the glory as you stare into the sky.",
  "You are the true master of death, because the true master does not seek to run away from Death. He accepts that he must die, and understands that there are far, far worse things in the living world than dying.",
  "There's a club if you'd like to go. You could meet somebody who really loves you. So you go and you stand on your own and you leave on your own and you go home and you cry and you want to die.",
  "Some feeling had started in my stomach and was traveling up to my face, and I knew that when it got there I would turn bright red and hear the ocean, which is what happens when I get put on the spot.",
  "And so we meet at last. You are to be commended for avoiding my traps. The work of a man who once had too much time on his hands, and now finds time for nothing but the work of salvation.",
  "A choice tells the world what is most important to a human being. When a man has a choice to make he chooses what is most important to him, and that choice tells the world what kind of a man he is.",
  "You can tell from the lines on her face, you can see that she's been there. Probably been moved on from every place 'cause she didn't fit in there.",
  "With people like us, you should hang out, get to know what they do, how they do it. No one is going to answer questions like that. You need to understand how young people live on the streets.",
  "Love can touch us one time and last for a lifetime and never let go till we're one. Love was when I loved you one true time I hold to in my life we'll always go on.",
  "I don't care if they like me. I didn't come here to make friends. I don't even care if they respect me. I know who I am. I've got enough respect for myself. I do not want them to beat me.",
  "But I would walk five hundred miles and I would walk five hundred more, just to be the man who walks a thousand miles to fall down at your door.",
  "Because you're like a story that hasn't happened yet. Because I want to see what you will do. I want to be part of the unfolding of the tale.",
  "I've been fighting to be who I am all my life. What's the point of being who I am, if I can't have the person who was worth all the fighting for?",
  "There's something moving through the windows and walls, I've seen it before, seen it before. You left me living with a lingering soul, how little you know, how little you know.",
  "I still remember these old country lanes when we did not know the answers.",
  "Sometimes at night I let it get to me. And sometimes, I'm sure it gets to all of us. And last night, it had me down I'm feeling numb. I can try, but sometimes that is not enough. No, sometimes that is not enough.",
  "You can't look me in the eye and say that you love me and you know it. You know, there's no sense in struggling against a thing when it's got you. It's got you and that's all there is to it - it's got you!",
  "Sometimes I wish I never built this palace, but real love is never a waste of time.",
  "As long as we don't have magic, they will never treat us with respect. They need to know we can hit them back. If they burn our homes, we burn theirs, too.",
  "After others have talked about themselves, a point will be reached when the conversation will get around to you. A little patience here is well invested.",
  "Just one day, if I can be with you. Just one day, if I can hold your hands. Just one day, if I can be with you. Just one day, if only we can be together.",
  "There are two ways of seeing: with the body and with the soul. The body's sight can sometimes forget, but the soul remembers forever.",
  "Sometimes someone says something and their words are like the catch of a gas stove, the click, click while you're waiting for it to light up and flame big and blue...",
  "I hated that having done the right thing was somehow considered wrong. And I hated that there didn't seem to be any other way to survive school.",
  "Stupid, pitiful creature. I am the rage in your heart. I am the fury in your thoughts. I alone empowered you to bring chaos to this world, and by the endless void, you shall!",
  "Think of all the roads, think of all their crossings. Taking steps is easy, standing still is hard. Remember all their faces, remember all their voices. Everything is different the second time around.",
  "Apparently, it only appears to those people who are pure of heart and have a strong desire to see it.",
  "I think that those two people want to be together. I think that love, at the end of the day, is stronger than some mistake somebody made; something they did that they regret. I think that love allows for forgiveness.",
  "While monsters are mostly made of magic, human beings are mostly made of water.",
  "There is some love that will not go away. You're here, there's nothing I fear and I know that my heart will go on. We'll stay forever this way, you are safe in my heart.",
  "How can I just let you walk away, just let you leave without a trace? When I stand here taking every breath with you, you're the only one who really knew me at all.",
  "When the night has come and the land is dark and the moon is the only light we'll see, no I won't be afraid, oh, I won't be afraid just as long as you stand, stand by me.",
  "I had considered how the things that never happen are often as much realities to us, in their effects, as those that are accomplished.",
  "The point is that if you are a little different, or a little outrageous, or if you do things that are bold or controversial, the press is going to write about you.",
  "I know he tried, and he's still trying, and he'll still make mistakes sometimes, because he's a human being, and I've learned now that this is what human beings are always destined to do. Including me.",
  "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason.",
  "It's where I learned about living, it's where I learned about love. It's where I learned about working hard, and having a little was just enough.",
  "I don't know where you're going and I don't know why but listen to your heart before you tell him goodbye. Sometimes you wonder if this fight is worthwhile. The precious moments are all lost in the tide.",
  "I would never want to belong to any club that would have someone like me as a member. That's the key joke of my adult life in terms of my relationships with women.",
  "I only know that learning to believe in the power of my own words has been the most freeing experience of my life. It has brought me the most light. And isn't that what a poem is? A lantern glowing in the dark.",
  "And you can fly high as a kite if you want to, faster than light if you want to, speeding through the universe. Thinking is the best way to travel.",
  "There will be no more retribution, so you better not waste your time. I don't miss your arms around me. I put my hands in the fire when it burned me once, I don't need it for a second time.",
  "There will come a time when there are no human beings remaining to remember that anyone ever existed or that our species ever did anything.",
  "You remind me that I am a mere mortal and you are a prince of Faerie. Well, let me remind you that means you have much to lose and I have nothing.",
  "It had never occurred to him until then to think that literature was the best plaything that had ever been invented to make fun of people...",
  "And that's how you go on. You lay laughter over the dark parts. The more dark parts, the more you have to laugh. With defiance, with abandon, with hysteria, any way you can.",
  "Sometimes terrible things happen, but there's nothing more terrible than not having anybody to tell it to.",
  "So you were born, and that was a good day. Someday you'll die, and that is a shame. But somewhere in the between was a life in which we all dream. And nothing and no one will ever take that away.",
  "All I'm asking is that you do the minimal amount of work in this class to give yourself the illusion that you're actually learning something, and to give me a modicum of self respect like I'm actually teaching a class.",
  "Stay, you're not gonna leave me. This place is right where you need to be. And why your words gotta mean so much to them? They mean nothing to me.",
  "In that cell you found something that mattered more to you than life.",
  "There is no difference between time and any of the dimensions of space except that our consciousness moves along it.",
  "This is what we call love. When you are loved, you can do anything in creation. When you are loved, there's no need at all to understand what's happening, because everything happens within you.",
  "In a very real sense we have two minds, one that thinks and one that feels.",
  "I cannot fix on the hour, or the spot, or the look or the words, which laid the foundation. It is too long ago. I was in the middle before I knew that I had begun.",
  "Many people say that even if they don't know much about many things, at least they know what they like. But no, sorry sucker, hard luck!",
  "What a lamentable thing it is that men should blame the gods and regard us as the source of their troubles, when it is their own transgressions which bring them suffering that was not their destiny.",
  "Whoever said that practice makes perfect is an idiot. Humans can't be perfect because we are not machines. The best thing that you can say about practice is that it makes better.",
  "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
  "Good games offer players a set of challenging problems and then let them practice these until they have routinized their mastery.",
  "Five thousand of my men are out there in the freezing mud. Three thousand of them are bloodied and cleaved. Two thousand will never leave this place. I will not believe they fought and died for nothing.",
  "For we are not as faithful to the being we have most loved as we are to ourselves and sooner or later we forget her - since that is one of our characteristics - so as to start loving another.",
  "He could not be mistaken. There were no other eyes like those in the world. There was only one creature in the world who could concentrate for him all the brightness and meaning of life. It was she. It was Kitty.",
  "I can't believe I used to love the first day of school.",
  "Ticking away the moments that make up a dull day, you fritter and waste the hours in an off-hand way. Kicking around on a piece of ground in your home town, waiting for someone or something to show you the way.",
  "Most of all I want to sleep. I want to sleep like I slept when I was a boy. Give me that. Just one time. That's why I won't allow that punk out there to get the best of me. Let alone the last of me.",
  "It's better to read in the library. Sitting at my favorite table by the window reading and listening to the sound of other folks turning pages makes me feel like I'm in a house full of company I don't have to talk to.",
  "The Earth is a world, the world is a ball, a ball in a game with no rules at all. And just as I wonder at the beauty of it all, you go and drop it and it breaks and falls.",
  "At that time, I often thought that if I had had to live in the trunk of a dead tree, with nothing to do but look up at the sky flowing overhead, little by little I would have gotten used to it.",
  "Cardan looks at me as though he's never seen me before. He looks at me as though no one has ever spoken to him like this. Maybe no one has.",
  "And in the end, it's not the years in your life that count: It's the life in your years.",
  "I do not know what evil is when it comes to art. I only know what is good art and what is bad art.",
  "For all my brave talk, I knew it was just that. No matter how much I trained or how much I studied, the best test score in the world wasn't gonna matter unless I had the blood test to go with it.",
  "History is not merely a linear collection of points that we pass through on a timeline. They are connected by a line. No, perhaps it is more accurate to say that they are made to connect.",
  "What incensed him the most was the blatant jokes of the ones that passed it all off as a jest, pretending to understand everything and in reality not knowing their own minds.",
  "Children know something that we all too often set aside once we enter adulthood - that one of the best things in life is an experience designed to give you nothing more than glee.",
  "I'm not very good at this, out, being in public. But I felt the need to speak up for this city that I love with all my heart. No one should have to live in fear, in fear of madmen who have no regard for who they injure.",
  "How lovely would it feel to sing like that, to change the air with my voice, to fill people's ears with such pleasure. The sound cleared its own space and made it seem like everything was okay again.",
  "You once thought of me as a white knight on his steed. Now you know how happy I can be. Our good times start and end without dollar one to spend.",
  "If I could fall into the sky, do you think time would pass me by?",
  "I don't give a damn, except that I get bored sometimes when people tell me to act my age. Sometimes I act a lot older than I am - I really do - but people never notice it. People never notice anything.",
  "Sometimes I wondered if I was seeing the same things through my eyes that the rest of the world was seeing through theirs. Maybe there was a glitch in my brain.",
  "To the extent that experience is the sum of our memories and wisdom the sum of experience, having a better memory would mean knowing not only more about the world, but also more about myself.",
  "When every card in the deck is stacked against you, the only way to win a hand is to break the rules.",
  "I thought I had it all together, but I was led astray the day you walked away. You were the clock that was tickin' in my home. Changed my state of mind. Love's so hard to find.",
  "I wish I could just make you turn around and see me cry. There's so much I need to say to you. So many reasons why you're the only one who really knew me at all.",
  "It's just that I learned a while ago that the best way to get people to like you is not to like them too much.",
  "If we burn our wings flying too close to the sun; if the moment of glory is over before it's begun; if the dream is won though everything is lost, we will pay the price but we will not count the cost.",
  "The capacity to love is determined by the fact that man is ready to seek the good consciously with others, to subordinate himself to this good because of others, or to subordinate himself to others because of this good.",
  "You don't know what you're trying to take from me. You don't like it messy, but it's going to get as messy as it wants to be. Wind me up, set me down and look away. I can see the bottom, and the bottom's okay.",
  "What are you doing on my boat? Look, I've had a really bad day and I just need your help. You see, I've been thrown out of my home and flushed down my own toilet.",
  "Dreams are not to be converted into reality, that we know; we would not form any, perhaps, were it not for desire, and it is useful to us to form them in order to see them fail and to be instructed by their failure.",
  "You're horrible. You make up this story about demons talking to you through plastic animals when nothing talks to you just like nothing talks to me.",
  "Where did I go wrong? I lost a friend somewhere along in the bitterness and I would have stayed up with you all night had I known how to save a life.",
  "We can experience nothing but the present moment, live in no other second of time, and to understand this is as close as we can get to eternal life.",
  "Everyone wants stuff. We wake up every day with a list of wishes a mile long and maybe we spend our lives trying to make those wishes come true, but just because we want them doesn't mean we need them to be happy.",
  "Sam was the only member of the party who had not been over the river before. He had a strange feeling as the slow gurgling stream slipped by: his old life lay behind him in the mists, dark adventure lay in front.",
  "We imagine that when we are thrown out of our usual ruts all is lost, but it is only then that what is new and good begins. While there is life there is happiness. There is much, much before us.",
  "When for years you wake up to having to win every battle every day, to prove that you are the best at everything... I started to worry what would happen if it turned out that I wasn't the best. I didn't want to worry...",
  "Well, if that's how you feel about it, then that's how you feel about it. Is that how you feel about it?",
  "The last man on Earth sat alone in a room. There was a knock on the door.",
  "He supposed that even in Hell, people got an occasional sip of water, if only so they could appreciate the full horror of unrequited thirst when it set in again.",
  "I'll close my eyes. Then I won't see the love you don't feel when you're holding me. Morning will come, and I'll do what's right. Just give me till then to give up this fight.",
  "Remember that humor is written backwards. That means you first find the cliche you want to work on, then build a story around it.",
  "Now and again we try to just stay alive, maybe we'll turn it all around 'cause it's not too late. It's never too late.",
  "A straight line is said to have been cut in extreme and mean ratio when, as the whole line is to the greater segment, so is the greater to the lesser.",
  "Why did I do it? Mainly because people said it was impossible, and that's what my life is all about: breaking limitations and showing people what our memories are capable of.",
  "I can hear the soft breathing of the girl that I love as she lies here beside me asleep with the night. And her hair, in a fine mist floats on my pillow, reflecting the glow of the winter moonlight.",
  "And the hardest part was letting go, not taking part was the hardest part. And the strangest thing was waiting for that bell to ring. It was the strangest start.",
  "For my hope was founded on a fat man in Bree; and my fear was founded on the cunning of Sauron. But fat men who sell ale have many calls to answer; and the power of Sauron is still less than fear makes it.",
  "It is not despair, for despair is only for those who see the end beyond all doubt. We do not.",
  "We've wounded this mountain. It's our duty to close her wounds. It's the least we can do to show our gratitude for all the wealth she's given us. If you guys don't want to help me, I'll do it alone.",
  "I've never really had much of an imagination. But still I would try to picture the exact moment when the beating of my heart would no longer be going on inside my head.",
  "And I taught myself how to forget that sometimes life will try to convince you there's such a thing as regret. But I found it to be a lie, the same lie I found when I looked in your eyes after it was said and done.",
  "If you had one shot to sit on your lazy butt, and watch all the TV you ever wanted, until your brain turned to mush. Would you go for it, or just let it slip?",
  "I've never been to this part of the castle, at least while awake. I sleepwalk you see, that's why I wear shoes to bed.",
  "Look into my eyes and it's easy to see, one and one make two, two and one make three, it was destiny. Once every hundred thousand years or so, when the sun doth shine and the moon doth glow and the grass doth grow.",
  "In the midst of friends, home, and kind parents, she was alone.",
  "It seemed funny to me that the sunset she saw from her patio and the one I saw from the back steps was the same one. Maybe the two different worlds we lived in weren't so different. We saw the same sunset.",
  "When you hit rock-bottom, you still have a way to go until the abyss.",
  "It was not the brutality of what occurred next that changed my mind and brought home to me the full meaning of fear. It was the brilliance of it.",
  "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.",
  "There is a theory, for which there is much to be said, that gold and gems were valued originally on account of their supposed magical properties.",
  "Every day when you're walking down the street, everybody that you meet has an original point of view. And I say hey, hey! What a wonderful kind of day, where you can learn to work and play, and get along with each other.",
  "In the beginning, the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.",
  "I want you to know that the day you saw something in me, my whole life changed.",
  "Your silence furnishes a dark house. But even at the risk of burning, the moth always seeks the light.",
  "It was the last that remained of a past whose annihilation had not taken place because it was still in a process of annihilation, consuming itself from within, ending at every moment but never ending its ending.",
  "The gentleman cannot be appreciated in small things but is acceptable in great matters. A small man is not acceptable in great matters but can be appreciated in small things.",
  "There was no reason for me to stay in the real world any longer. In the real world, it didn't matter if I was there or not. When I realized that, I was no longer afraid of losing my body.",
  "There's a storm coming, Mr. Wayne. You and your friends better batten down the hatches, because when it hits, you're all gonna wonder how you ever thought you could live so large and leave so little for the rest of us.",
  "I breathed in my new surroundings. The air smelled different here, I don't know whether it was the desert air or the dry trees or just that I was far away from the stink of the city, but I liked it.",
  "Why is it, every time something terrible happens, everyone tells you the worst thing that ever happened to them, as though that makes it easier?",
  "Let me photograph you in this light, in case it is the last time that we might be exactly like we were before we realized we were sad of getting old.",
  "There's a sign on the wall but she wants to be sure 'cause you know sometimes words have two meanings. In a tree by the brook, there's a songbird who sings, sometimes all of our thoughts are misgiven.",
  "You gotta see it to believe it, the sky never looked so blue it's so hard to leave it, but that's what I always do. So I keep thinking back to a time under the canyon moon.",
  "Learn to light a candle in the darkest moments of someone's life. Be the light that helps others see; it is what gives life its deepest significance.",
  "What I think is if you can't figure out how to have a simple date with a woman who's already agreed to go out with you, then maybe you don't deserve to go out with her in the first place. How's that for advice?",
  "You cannot fly with the eagles if you continue to scratch with the turkeys.",
  "They say there is a person who will tell you how to survive in this land... Oh, wait. That's me.",
  "When I was your age, television was called books. And this is a special book. It was the book my father used to read to me when I was sick, and I used to read it to your father. And today I'm gonna read it to you.",
  "It's important in life to conclude things properly. Only then can you let go. Otherwise you are left with words you should have said but never did, and your heart is heavy with remorse.",
  "The journey doesn't end here. Death is just another path, one that we all must take. The grey rain-curtain of this world rolls back, and all turns to silver glass, and then you see it.",
  "And so with the sunshine and the great bursts of leaves growing on the trees, just as things grow in fast movies, I had that familiar conviction that life was beginning over again with the summer.",
  "You shared something horrible with me, gave me no time to process it, and while I was taking it in you not only attacked my integrity, you made me feel ashamed of myself.",
  "Everyone gets everything he wants. I wanted a mission, and for my sins, they gave me one. Brought it up to me like room service. It was a real choice mission, and when it was over, I never wanted another.",
  "You must have a goal because it's just as difficult to reach a destination you don't have, as it is to come back from a place you've never been.",
  "You can't see the changes we see, we who have been with him for so long. Do you think any of us want to look into his eyes for the next hundred years if he loses you?",
  "I can hear those echoes in the wind at night calling me back in time, back to you, in a place far away where the water meets the sky.",
  "Yes, it was her he was looking at, and there was meaning in his look. His eyes burned into her as though they would search her through and through, read her very soul.",
  "This was supposed to be a question. Not a poem, confession or whatever it's become. I just want to know if you would listen with me to the sound of our heartbeats.",
  "I have a dream, a song to sing, to help me cope with anything. If you see the wonder of a fairy tale you can take the future even if you fail.",
  "You'll never have that kind of relationship in a world where you're afraid to take the first step because all you see is every negative thing ten miles down the road.",
  "Although his voice was also broken by uncertainty and his hands seemed to doubt the existence of things, it was evident that he came from the world where men could still sleep and remember.",
  "Give me a lifetime of promises and a world of dreams. Speak the language of love like you know what it means. You're simply the best, better than all the rest, better than anyone I ever met.",
  "I have noticed even people who claim everything is predestined, and that we can do nothing to change it, look before they cross the road.",
  "The thing under my bed waiting to grab my ankle isn't real. I know that, and I also know that if I'm careful to keep my foot under the covers, it will never be able to grab my ankle.",
  "You know when I was your age, I went out to fishing with all my brothers and my father, and everybody. And I was the only one who caught a fish.",
  "The highlander seemed to float through life very much the same as a cloud in an empty sky, touching nothing, leaving no trace of his passing.",
  "His ear heard more than what was said to him, and his slow speech had overtones not of thought, but of understanding beyond thought.",
  "It's not about changing the world. It's about doing our best to leave the world the way it is. It's about respecting the will of others, and believing in your own.",
  "Perhaps love is like a resting place, a shelter from the storm. It exists to give you comfort. It is there to keep you warm. And in those times of trouble when you are most alone, the memory of love will bring you home.",
  "Did you know? There are three kinds of aces. Those who seek strength, those who live for pride, and those who can read the tide of battle.",
  "If all these dreams might find their way into my day to day scene I'd be under the impression I was somewhere in between. With only two, just me and you. Not so many things we got to do or places we got to be.",
  "After several hours, Joe finally gave up on logic and reason, and simply told the cabinet that he could talk to plants and that they wanted water.",
  "But older than me now, more constant, more real, and the fur, and the mouth, and the innocence turned to hair and contentment that hangs in abasement - a woman now standing where once there was only a girl.",
  "If you want to save yourself the ticket price, go into the kitchen, cue up a male choir singing the music of hell, and get a kid to start banging pots and pans together. Then close your eyes and use your imagination.",
  "Pause you who read this, and think for a moment of the long chain of iron or gold, of thorns or flowers, that would never have bound you, but for the formation of the first link on one memorable day.",
  "They often wish that people would just once and for all work out where the hell they wanted to be.",
  "I suppose it is tempting, if the only tool you have is a hammer, to treat everything as if it were a nail.",
  "All of these moments just might find their way into my dreams tonight. But I know that they'll be gone when the morning light sings and brings new things.",
  "The major difference between a thing that might go wrong and a thing that cannot possibly go wrong is that when a thing that cannot possibly go wrong goes wrong it usually turns out to be impossible to get at or repair.",
  "There are many people who reach their conclusions about life like schoolboys; they cheat their master by copying the answer out of a book without having worked out the sum for themselves.",
  "I came back home from work tonight and saw you there, with a train set in your hands and paint in your hair. And I just saw you this morning but I don't care; I'm saying let's never be apart again.",
  "Anywhere can be paradise, as long as you have the will to live. After all, you are alive, so you will always have the chance to be happy.",
  "We got questions we should not ask, but how would you feel if I told you I loved you? It's just something that I want to do.",
  "I etched your name in the clouds but it was lost when the thunder cried. I etched your name in the surf but it was stolen by the rising tide. I etched your name in my heart and there it will forever reside.",
  "I wrote about how last weekend my parents and I waited in line at the movies for an hour, and when we finally got up to the ticket booth lady, they were sold out! Isn't that sad?",
  "Nice things don't happen in storybooks. Or when they do happen, something bad happens next. Because otherwise the story would be boring, and no one would read it.",
  "You can't get back what you've lost, what's important now is what it is that you still have.",
  "And one day I knew I had to come back here. I had to come back and get on the merry-go-round, and eat cotton candy, and listen to a band concert. Just stop and breathe, and close my eyes and smell and listen.",
  "But the law of loving others could not be discovered by reason, because it is unreasonable.",
  "For string theory to make sense, the universe should have nine space dimensions and one time dimension, for a total of ten dimensions.",
  "But on this particular day I did not like the color of the sky.",
  "On the page, punctuation performs its grammatical function, but in the mind of the reader it does more than that. It tells the reader how to hum the tune.",
  "I can't have been there when brains were handed 'round or get past the cover of your books profound and some of your friends think it's really unsound that you're ever seen talking to me.",
  "Getting into trouble is not a bad thing. It's proof that someone's watching you. I've got my eyes on you, so feel free to mess up as much as you want.",
  "What a charming reconciler and peacemaker money is!",
  "Life is not the amount of breaths you take. It's the moments that take your breath away.",
  "We climbed, he first and I behind, until through a small round opening ahead of us, I saw the lovely things the heavens hold, and we came out to see once more the stars.",
  "Death really did not matter to him but life did, and therefore the sensation he felt when they gave their decision was not a feeling of fear but of nostalgia.",
  "One more turn and I'll settle the score. A rubber fire screams into the night. Crash and burn is what you're gonna do. I am the master of the asphalt fight.",
  "Being in a minority, even in a minority of one, did not make you mad. There was truth and there was untruth, and if you clung to the truth even against the whole world, you were not mad.",
  "The creatures outside looked from pig to man, and from man to pig, and from pig to man again; but already it was impossible to say which was which.",
  "Life is very short, and there's no time for fussing and fighting, my friend. I have always thought that it's a crime, so I will ask you once again, try to see it my way. Only time will tell if I am right or I am wrong.",
  "All these fears and all this love, all you've given me, it's not enough. All my dreams and all this stuff, all made real... it's not enough.",
  "I'd like to see the world for once all standing hand in hand and hear them echo through the hills for peace throughout the land.",
  "It was the most horrible, the most repellent thing she had ever seen, far more nauseating than anything she had ever imagined with her conscious mind, or that had ever tormented her in her most terrible nightmares.",
  "I'll light the fire, you place the flowers in the vase that you bought today. Staring at the fire for hours and hours while I listen to you. Play your love songs all night long for me, only for me.",
  "Tonight I'm making deals with the devil, and I know it's gonna get me in trouble. Just as long as you know you got me.",
  "That'll be a dispute to the end of time, Mr. Brown: whether it's better to do the right thing for the wrong reason or the wrong thing for the right reason.",
  "Come let me love you, let me give my life to you, let me drown in your laughter, let me die in your arms, let me lay down beside you, let me always be with you.",
  "There are places I'll remember all my life, though some have changed. Some forever, not for better. Some have gone and some remain. All these places have their moments with lovers and friends I still can recall.",
  "I am doing good to the poor, but I differ in opinion about the means. I think the best way of doing good to the poor is not making them easy in poverty, but leading them or driving them out of it.",
  "At last, we finally meet. I have something for you, Chancellor; a farewell gift. For all the things you've done, for the things you might have done, and for the only thing you have left.",
  "It's a thousand pages, give or take a few. I'll be writing more in a week or two. I could make it longer if you like the style. I can change it 'round, and I want to be a paperback writer.",
  "It doesn't matter what I say, so long as I sing with inflection that makes you feel I'll convey some inner truth or vast reflection. But I've said nothing so far, and I can keep it up for as long as it takes.",
  "I have moments like that a lot, when my brain falls asleep or something, and the next thing I know I've missed something, as if a puzzle piece fell out of the universe and left me staring at the blank place behind it.",
  "I've tried to hide it so that no one knows, but I guess it shows. When you look into my eyes, what you did and where you are coming from, I don't care as long as you love me.",
  "Don't tell me what's in, don't tell me how to write, don't tell me how to win this fight. It isn't your right, isn't your life, it isn't your right to take the only thing that's mine.",
  "Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?",
  "They can only see the mere show, and never can tell what it really means.",
  "In general, people only ask for advice that they may not follow it; or, if they should follow it, that they may have somebody to blame for having given it.",
  "I only lose my fear when I run. I won't lose a tear when I run. I won't find a heart so I run. And now the time is right so we run.",
  "You can have my isolation, you can have the hate that it brings, you can have my absence of faith, you can have my everything.",
  "One day she left without a word, she took away the sun. And in the dark she left behind, I knew what she had done. She'd left me for another, it's a common tale but true.",
  "For the days of my life have vanished like smoke, and my bones are parched like ash, and let all my impurities be as fuel for that fire until nothing remains but the light alone.",
  "I took a walk alone last night, I looked up at the stars to try and find an answer in my life. I chose a star for me, I chose a star for him, I chose two stars for my kids and one star for my wife.",
  "Once you free your mind about a concept of harmony and music being correct you can do whatever you want. So, nobody told me what to do, and there was no preconception of what to do.",
  "What have I got to do to make you love me? What have I got to do to make you care? What do I do when lightning strikes me and I wake to find that you're not there?",
  "Wealth can be very empty when you don't have someone to share it with. But by the time I realized that, no one would have me except men who wanted my money more than I did.",
  "Got me thinking. I know what I love too. Family and friends. All the ones here and all ones gone. I love my dog, and this orchard, and a crumbledown house.",
  "Under the lights when everything goes. Nowhere to hide when I'm getting you close when we move, well, you already know.",
  "If you've had half as much fun watching the show as we've had doing it, well then we've had twice as much fun doing the show as you've had watching it.",
  "I want adventure in the great wide somewhere. I want it more than I can tell. And for once it might be grand to have someone understand; I want so much more than they've got planned.",
  "So if this was a touching romantic story this is probably where a new feeling would wash over me and suddenly we would be furiously making out with the fire of a thousand suns. But this isn't a touching romantic story.",
  "You don't need money, don't take fame. Don't need no credit card to ride this train. It's strong and it's sudden and it's cruel sometimes, but it might just save your life. That's the power of love.",
  "Blackbird singing in the dead of night, take these broken wings and learn to fly. All your life you were only waiting for this moment to arise.",
  "I remember way back then when everything was true and when we would have such a very good time. Such a fine time, such a happy time.",
  "It's a fallen situation when all eyes are turned in and a love isn't flowing the way it could have been. You brought it all on but it feels so wrong. You brought it all on. I don't believe this song.",
  "Language does for intelligence what the wheel does for the feet and the body. It enables them to move from thing to thing with greater ease and speed and ever less involvement.",
  "A year has passed since I wrote my note but I should have known this right from the start: only hope can keep me together; love can mend your life but love can break your heart.",
  "Nature never appeals to intelligence until habit and instinct are useless. There is no intelligence where there is no need of change.",
  "Fortune, which has a great deal of power in other matters but especially in war, can bring about great changes in a situation through very slight forces.",
  "Fools rush in where wise men never go, but wise men never fall in love so how are they to know? When we met I felt my life begin. So open up your heart and let this fool rush in.",
  "Maybe someday we can talk about our past and we can talk about the weather; whenever you leave I don't care what I'm remembered for, I just want to be remembered.",
  "Imagine you were born without a memory. Who would you be? You could be nothing; if you didn't have memory, you wouldn't be able to function in our world.",
  "In a hamlet of ten households, there are bound to be those who are my equal in doing their best for others and in being trustworthy in what they say, but they are unlikely to be as eager to learn as I am.",
  "I know there's something in the wake of your smile. I get a notion from the look in your eyes. You've built a love but that love falls apart. Your little piece of heaven turns to dark.",
  "Where are those happy days, they seem so hard to find. I tried to reach for you, but you have closed your mind. Whatever happened to our love? I wish I understood. It used to be so nice, it used to be so good.",
  "To put things simply, if your past makes your present... Then your present can and will make your future. When you think about it that way... You absolutely have the potential to be anything you want to be.",
  "If the world thinks you're a monster, what does it matter? The world is wrong. But when you start to think of yourself as a monster...",
  "Give me reasons we should be complete. You should be with him, I can't compete. You looked at me like I was someone else, oh well, can't you see? I don't wanna slow dance in the dark.",
  "Love isn't just wanting another person the way you want to own an object you see in a store. That's just desire. You want to have it around, take it home and set it up somewhere in the apartment like a lamp.",
  "In most cases, there is more to be gained by maximizing the performance of the driver than tricking out the car. The most important factor is the driver, the ultimate control system of a race car.",
  "She can kill with a smile, she can wound with her eyes, she can ruin your faith with her casual lies, and she only reveals what she wants you to see. She hides like a child, but she's always a woman to me.",
  "You have two choices: you can keep running and hiding and blaming the world for your problems, or you can stand up for yourself and decide to be somebody important.",
  "It is at this point in our story that along comes a spider.",
  "Who cares if we don't see the sun shine ever again? I want you more than any blue sky. The weather can go crazy.",
  "Sally and I did not know what to say. Should we tell her the things that went on there that day? Should we tell her about it? Now, what should we do? Well, what would you do if your mother asked you?",
  "As you decide, you shall be left as you were before, and neither richer nor wiser, unless the sense of service rendered to a man in mortal distress may be counted as a kind of riches of the soul.",
  "I realized that back then, the reason I wanted to become human was that I really just wanted to have friends. Now, I just want to be a monster that can help Luffy.",
  "We can now get these kids to buy just about anything. We can have them chasing a new trend every week. And that is good for the economy. And what's good for the economy is good for the country.",
  "In your heart I see the start of every night and every day. In your eyes I get lost, I get washed away. Just as long as I'm here in your arms I could be in no better place.",
  "The only ones who should kill are those prepared to be killed.",
  "For someone who was never meant for this world, I must confess I'm suddenly having a hard time leaving it.",
  "I am Dracula and I welcome you to my house. I must apologize for not being here to greet you personally, but I trust you've found everything you needed.",
  "There can be no light without the dark, and so it is with magic. Myself, I always strive to live within the light. Is that what you told Tom Riddle, sir, when he came asking questions?",
  "I know that you wanna but you can't 'cause you gotta stay cool in the corner when the truth is that you wanna move.",
  "Well, the real reason that you've been sent over here is because they wanted you to be evaluated... to determine whether or not you are mentally ill. This is the real reason. Why do you think they might think that?",
  "A good plan today is better than a perfect plan tomorrow.",
  "You spend your life in a dream that you can't escape, 'cause you live your life in a coma, you're never awake. If you'd open your eyes then maybe you'd see what's at stake. You're sleeping. You're sleeping.",
  "This is a life-or-death elimination match. The only way to survive... is to win. There can be no doubt that those are the rules of the game. Which is why I am bowing out of the game.",
  "For children love is a feeling; for adults, it is a decision. Children wait to learn if their love is true by seeing how long it lasts; adults make their love true by never wavering from their commitment.",
  "Our emotions cloud our perceptions. It's no wonder this library is the most wonderful place on earth to you, but other people don't see it that way.",
  "I needed all the feelings to stop boiling like a pot of dal and be cool enough for me to taste them.",
  "Although some men who were easy with their words said that it was worth sacrificing one's life for a night of love with such an arousing woman, the truth was that no one made any effort to do so.",
  "In the short term, it would make me happy to go play outside. In the long term, it would make me happier to do well at school and become successful. But in the very long term, I know which will make better memories.",
  "But I believe in true love, you know? I don't believe that everybody gets to keep their eyes or not get sick or whatever, but everybody should have true love, and it should last at least as long as your life does.",
  "Everybody knows in their bones that something is eternal, and that something has to do with human beings.",
  "Man, don't tell me how good I was. I just got away with it because I had a hangover. I was too mad to be scared and too sick to worry about it. You know that.",
  "You do not have to sit outside in the dark. If, however, you want to look at the stars, you will find that darkness is necessary. But the stars neither require nor demand it.",
  "I'm just not the guy for you. I mean, you need a guy who's happy and perky all the time. Maybe a guy who's had part of his brain removed and he thinks he's a bunny and you can go off and be bunnies together.",
  "How sweet it is to love someone, how right it is to care. How long it's been since yesterday, what about tomorrow, and what about our dreams and all the memories we share?",
  "The night's always waiting, still and unseen. The harder you focus, the darker it seems.",
  "It's the job that's never started as takes longest to finish, as my old gaffer used to say.",
  "Perhaps love is like a window, perhaps an open door. It invites you to come closer. It wants to show you more. And even if you lose yourself, and don't know what to do, the memory of love will see you through.",
  "There's a feeling I get when I look to the west and my spirit is crying for leaving. In my thoughts I have seen rings of smoke through the trees and the voices of those who stand looking.",
  "Here we go, another night out. Waited all week just to get out. Where do we come from? Do I know your name? Doesn't really matter; in this life we're all the same. Move for me, I'll move for you.",
  "But no matter how effective the lesson was, I never really used it after that. I didn't enjoy doing it that way. But it was interesting to know that things worked much differently from how I was brought up.",
  "I just told you the truth. I told you the truth the first time. You don't have to ask me again. I never do that. I always tell you the truth. If I did it, you would know. I took her out a couple of times.",
  "I suppose I could collect my books and get on back to school or steal my daddy's cue and make a living out of playing pool or find myself a rock and roll band that needs a helping hand.",
  "It's a funny thing, but people mostly have it backward. They think they live by what they want. But really, what guides them is what they're afraid of. What they don't want.",
  "Sometimes you are too ashamed to leave. That was true now. And sometimes you need too much to know the facts, and so humbly and stupidly you stay.",
  "People running everywhere, don't know the way to go, don't know where I am. Can't see past the next step, don't have to think past the last mile, have no time to look around. Just run around, run around and think why.",
  "I'd have wasted a lot of time and trouble before I learned that the best way to take all people, black or white, is to take them for what they think they are, then leave them alone.",
  "So I walk into the sun. I thought you'd be there, but you could fool anyone. In the red water dust, will I see you soon, or did we move on?",
  "You have to accept that sometimes that's how things happen in this world. People's opinions, their feelings, they go one way, then the other. It just so happens you grew up at a certain point in this process.",
  "Patience, he thought. So much of this was patience - waiting, and thinking and doing things right. So much of all this, so much of all living was patience and thinking.",
  "If I am to serve both as a waitress and the butt of jokes, I think I should make more money.",
  "She knew since she was little, the world would not sing her triumphs, but she took all of the stereotypes and put them in a chokehold until they breathed out the truth.",
  "I never thought I'd be able to do any of this stuff. But I can. Anyone can wear the mask. You could wear the mask. If you didn't know that before, I hope you do now.",
  "I don't want to talk about the things we've gone through. Though it's hurting me, now it's history. I've played all my cards and that's what you've done too. Nothing more to say, no more ace to play.",
  "Mother used to say that however miserable one is, there's always something to be thankful for. And each morning, when the sky brightened and light began to flood my cell, I agreed with her.",
  "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
  "I do not deny that what happened to us is a thing worth laughing at. But it is not worth telling, for not everyone is sufficiently intelligent to be able to see things from the right point of view.",
  "Today is gonna be the day that they're gonna throw it back to you. By now you should've somehow realized what you gotta do. I don't believe that anybody feels the way I do about you now.",
  "A hero can be anyone. Even a man doing something as simple and reassuring as putting a coat around a young boy's shoulders to let him know that the world hadn't ended.",
  "He spent six hours examining things, trying to find a difference from their appearance on the previous day in the hope of discovering in them some change that would reveal the passage of time.",
  "You know better than you think you know, and you shall live to know me better yet.",
  "There must be quite a few things a hot bath won't cure, but I don't know many of them.",
  "When you meet someone better than yourself, turn your thoughts to becoming his equal. When you meet someone not as good as you are, look within and examine your own self.",
  "Why are you the way that you are? Honestly, every time I try to do something fun or exciting, you make it not... that way. I hate so much about the things that you choose to be.",
  "I hope you still feel small when you stand beside the ocean. Whenever one door closes I hope one more opens. Promise me that you'll give faith a fighting chance when you get the choice to sit it out or dance.",
  "If you want a happy ending, that depends, of course, on where you stop your story.",
  "Whenever there is a meeting, a parting shall follow. But that parting needs not last forever. Whether a parting be forever or merely for a short while... that is up to you.",
  "The man who pulls the lever that breaks your neck will be a dispassionate man, and that dispassion is the very essence of justice. For justice delivered without dispassion is always in danger of not being justice.",
  "When someone betrays your trust, it feels like a part of you dies. For me, I guess it was the part that cared.",
  "Remembering you standing quiet in the rain as I ran to your heart to be near. And we kissed as the sky fell in holding you close how I always held close in your fear.",
  "People just don't understand what is involved in this. This is an art form! You know, I think that most people just think that I hold a camera and point at stuff, but there is a heck of a lot more to it than just that.",
  "You must follow me carefully. I shall have to controvert one or two ideas that are almost universally accepted. The geometry, for instance, they taught you at school is founded on a misconception.",
  "I don't know what it is about you, but I feel like myself when I'm with you, but the way I always wanted to feel, because I'm in love with you Megan, and I think I have been for a while.",
  "I must have done something right, to deserve you in my life... I must have done something right along the way.",
  "If everyone keeps asking you the same questions, maybe you have to come up with new answers just to stay awake.",
  "All we need for morality is contained in these words: make others happy as you yourself would be, and serve them in the way you would yourself be served. The sole requirement is a good heart.",
  "I just feel like there are so many things that I could be doing and probably want to be doing that I'm just not.",
  "Since painting embraces within itself all the forms of nature you have nothing omitted except the names, and these are not universal like the forms.",
  "I see a line of cars and they're all painted black with flowers and my love, both never to come back. I see people turn their heads and quickly look away. Like a new born baby, it just happens every day.",
  "But I got smarter, I got harder in the nick of time. Honey, I rose up from the dead, I do it all the time. I got a list of names and yours is in red, underlined. I checked it once, then I checked it twice.",
  "Middle management means that you got just enough responsibility to listen when people talk, but not so much you can't tell anybody to go screw themselves.",
  "And though it's always been with me, I must tear down the wall and let it be. All I am, and all that I was ever meant to be, in harmony, shining true and smiling back at all who wait to cross. There is no loss.",
  "I feel it in my fingers, I feel it in my toes. Love is all around me and so the feeling grows. It's written on the wind, it's everywhere I go. So if you really love me, come on and let it show.",
  "After snow comes up, the wind blows it around so it looks like it's coming down but actually it comes up out of the ground - like grass. It comes up, Charlie Brown, snow comes up!",
  "The less you do with the controls, the less chance of error. Steer, shift, and use the pedals smoothly, and with finesse - not with blinding speed and brute force. The slower you move, the faster the car moves.",
  "They're talking about things of which they don't have the slightest understanding, anyway. It's only because of their stupidity that they're able to be so sure of themselves.",
  "The main thing to do is pay attention. Pay close attention to everything, notice what no one else notices. Then you'll know what no one else knows, and that's always useful.",
  "The rain fell slow, down on all the roofs of uncertainty. I thought of you, and the years and all the sadness fell away from me. And did you know... I never thought that you'd lose the light in your eyes?",
  "Even in the darkest times and places, there were always good people. People who would help others out of the kindness of their hearts.",
  "This combinatory play seems to be the essential feature in productive thought - before there is any connection with logical construction in words or other kinds of signs which can be communicated to others.",
  "You have technicians here making noise. No one is a musician, they are not artists because nobody can play the guitar.",
  "People go missing around here, they're gone for good. Outsiders come, they don't know where to walk. They bring trouble. We just want to be left alone. And so does he.",
  "The distinguishing mark of man is the hand, the instrument with which he does all his mischief.",
  "Tell me again, was it love at first sight when I walked by and you caught my eye? Didn't you know love could shine this bright? Well, smile because you're the deer in the headlights.",
  "I think you're still trying to figure out where you are. Where that ship of yours is. How to get back to that life.",
  "The dispositions of agents, their habitus, that is, the mental structures through which they apprehend the social world, are essentially the product of the internalization of the structures of that world.",
  "And men go abroad to admire the heights of mountains, the mighty billows of the sea, the broad tides of rivers, the compass of the ocean, and the circuits of the stars, and pass themselves by.",
  "The gentleman helps others to realize what is good in them; he does not help them to realize what is bad in them. The small man does the opposite.",
  "You're like the sun and I am Earth - together we're one. But someday your fire will die and I'll grow cold without sunlight.",
  "The pleasure of rooting for Goliath is that you can expect to win. The pleasure of rooting for David is that, while you don't know what to expect, you stand at least a chance of being inspired.",
  "Come on now, we're going to go build a mirror factory first and put out nothing but mirrors for the next year and take a long look in them.",
  "You are older than me. Do you still feel the pain of the scars that won't heal? Your eyes have died but you see more than I. Daniel, you're a star in the face of the sky.",
  "Kinda cold, walking home. Growing older on my own. Feels so strange to say when I am not alone. Faith will claim to be a friend to those she own but she will never try to call when I'm by the phone.",
  "One thing I've learned in the last seven years: in every game and con there's always an opponent, and there's always a victim. The trick is to know when you're the latter, so you can become the former.",
  "You've got a way to keep me on your side. You give me cause for love that I can't hide. For you I know I'd even try to turn the tide. Because you're mine, I walk the line.",
  "Formerly, when I would feel a desire to understand someone, or myself, I would take into consideration not actions, in which everything is relative, but wishes. Tell me what you want and I'll tell you who you are.",
  "All that is now, all that is gone, and everything under the sun is in tune but the sun is eclipsed by the moon.",
];
